[package]
name = "diskscout"
version = "0.1.0"
edition = "2021"
description = "A WizTree-style disk space analyzer for Linux"
authors = ["Berkay Parcal"]
repository = "https://github.com/RudblestThe2nd/diskscout"
license = "MIT"

[dependencies]
jwalk  = "0.8"
libc   = "0.2"
rayon  = "1.10"
eframe = "0.29"
egui   = "0.29"

[profile.release]
opt-level = 3
